### ISSUE TITLE
NLCD resolution

### ISSUE THREAD

**Issue by ZCWang95** [tbohn/NLCD_INEGI#2]
The "process_urban_lu_map.pl" thinks that the spatial resolution of NLCD map is 0.0003508840696170 degree. I'm not sure why this values was selected. But, this is not always the case. For example, the resolution I used is 0.000341219290263889 degree and this caused problem in the overlaying step. It'd be more reasonable to read the spatial resolution from the header of the nlcd map or from user input.

**Comment by tbohn** [comment]
I wrote it that way because I wanted all of my NLCD and INEGI rasters to have the same resolution (particularly along the US-Mexico border) so that I could merge them together.  But you're right, it's not good to hardcode things to that exact resolution. I've modified the code to grab the `cellsize` from the header of the `$nlcd_map` file and use that instead. See commit 79a3ede98199ec667fde1d8a5c7a33c95078cf27.
